Enhance RStudio server scripts for improved data directory management and logging
- Updated the RStudio data home path to a dedicated subdirectory within the job directory, enhancing organization.
- Added a directory creation step with error handling to ensure the data directory is successfully created, improving robustness.
- Adjusted the working directory setup in the script to utilize the new RSTUDIO_DATA_HOME, ensuring consistency across scripts.

diff --git a/var/www/ood/apps/sys/rstudio_server_app/template/before.sh.erb b/var/www/ood/apps/sys/rstudio_server_app/template/before.sh.erb
--- a/var/www/ood/apps/sys/rstudio_server_app/template/before.sh.erb
+++ b/var/www/ood/apps/sys/rstudio_server_app/template/before.sh.erb
@@ -29,11 +29,20 @@ fi
 export RSTUDIO_LOG_FILE="${JOB_DIR}/rstudio.log"
 export RSESSION_WRAPPER_FILE="${JOB_DIR}/rsession_wrapper.sh"
 export RSESSION_LOG_FILE="${JOB_DIR}/rsession.log"
-export RSTUDIO_DATA_HOME="${JOB_DIR}"
+export RSTUDIO_DATA_HOME="${JOB_DIR}/rstudio-data"
 
 echo "[before.sh.erb] RSTUDIO_LOG_FILE=${RSTUDIO_LOG_FILE}"
 echo "[before.sh.erb] RSESSION_LOG_FILE=${RSESSION_LOG_FILE}"
 echo "[before.sh.erb] RSTUDIO_DATA_HOME=${RSTUDIO_DATA_HOME}"
+
+# Create data dir
+mkdir -p "$RSTUDIO_DATA_HOME"
+if [[ $? -ne 0 ]]; then
+  echo "[before.sh.erb] ERROR: Failed to create directory ${RSTUDIO_DATA_HOME}"
+  exit 1
+else
+  echo "[before.sh.erb] Successfully created data directory."
+fi
 
 echo "[before.sh.erb] Setup complete."
 
